version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: Banco_de_dados_postgresql
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: MotosAluguel
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./MotosAluguel.Infra/Scripts:/docker-entrypoint-initdb.d

volumes:
  postgres-data: